version: '3.8'

services:
  copilot-metrics:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: copilot-metrics-hdi
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - NITRO_PORT=8080
