version: '3.8'

services:
  copilot-metrics:
    image: copilot-metrics-hdi:latest
    container_name: copilot-metrics-hdi
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - copilot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  copilot-network:
    driver: bridge
