# Configuración de Prometheus para HDI Copilot Metrics Viewer
# Monitoreo de métricas de aplicación y sistema

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'hdi-copilot-metrics'
    environment: 'production'

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus mismo
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # Aplicación Copilot Metrics
  - job_name: 'copilot-metrics-app'
    static_configs:
      - targets: ['copilot-metrics-viewer:3000']
    scrape_interval: 30s
    metrics_path: /api/metrics
    scrape_timeout: 10s
    honor_labels: true

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s
    metrics_path: /nginx_status
    scrape_timeout: 10s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Node Exporter (métricas del sistema)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Docker daemon
  - job_name: 'docker'
    static_configs:
      - targets: ['docker:9323']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

# Configuración de alertas
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Configuración de almacenamiento
storage:
  tsdb:
    retention.time: 30d
    retention.size: 1GB
